//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apartment_manager_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public string MaKhachHang { get; set; }
        public string TenKhachhang { get; set; }
        public string gioitinh { get; set; }
        public byte[] anh { get; set; }
        public string Macanho { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string quoctich { get; set; }
        public string dantoc { get; set; }
        public string sodienthoai { get; set; }
        public string quequan { get; set; }
        public string pathAnh { get; set; }
    }
}
